{{/* Setting defaults if they are omitted. */}}
{{- $pxMonitorEnabled := .Values.pxmonitor.enabled | default false }}
{{- if eq $pxMonitorEnabled true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pxcentral-monitor-post-install-setup
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: pxcentral-monitor-post-install-setup
{{- include "px-central.labels" . | nindent 4 }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pxcentral-monitor-post-install-setup
  labels:
    app.kubernetes.io/component: pxcentral-monitor-post-install-setup
{{- include "px-central.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "update", "create", "patch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["delete", "get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["patch", "update"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims", "persistentvolumes"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "update", "create", "patch"]
- apiGroups: ["extensions"]
  resources: ["ingresses", "ingresses/status", "networkpolicies"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "statefulsets", "deployments/status", "statefulsets/status"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "ingresses/status", "networkpolicies"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pxcentral-monitor-post-install-setup
  labels:
    app.kubernetes.io/component: pxcentral-monitor-post-install-setup
{{- include "px-central.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: pxcentral-monitor-post-install-setup
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: pxcentral-monitor-post-install-setup
  apiGroup: rbac.authorization.k8s.io
{{- end -}}