{{/* Setting defaults if they are omitted. */}}
{{- $UATLSType := .Values.pxlicenseserver.internal.lsTypeUAT -}}
{{- $AirgappedLSType := .Values.pxlicenseserver.internal.lsTypeAirgapped -}}
{{- $lsEnabled := .Values.pxlicenseserver.enabled | default false -}}
{{- if eq $lsEnabled true }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pxcentral-license-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: pxcentral-license-server
{{- include "px-central.labels" . | nindent 4 }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pxcentral-license-server
  labels:
    app.kubernetes.io/component: pxcentral-license-server
{{- include "px-central.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "update", "create", "patch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["delete", "get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["patch", "update"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims", "persistentvolumes"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "update", "create", "patch"]
- apiGroups: ["extensions"]
  resources: ["ingresses", "ingresses/status", "networkpolicies"]
  verbs: ["get", "list", "watch", "update", "create", "patch"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "statefulsets", "deployments/status", "statefulsets/status"]
  verbs: ["get", "list", "watch", "update", "create", "patch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "ingresses/status", "networkpolicies"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pxcentral-license-server
  labels:
    app.kubernetes.io/component: pxcentral-license-server
{{- include "px-central.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: pxcentral-license-server
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: pxcentral-license-server
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: pxcentral-license-server
{{- include "px-central.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: pxcentral-license-server
{{- include "px-central.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: pxcentral-license-server
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name | quote }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}